# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Interesting articles:
#  - https://www.runway.team/blog/how-to-build-the-perfect-fastlane-pipeline-for-android
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build a signed release AAB"
  lane :build_aab do
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      print_command_output: false,
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD']
      }
    )
  end

  desc "Build a signed release APK"
  lane :build_apk do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      print_command_output: false,
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD']
      }
    )
  end

  # Uses aab path for Github build
  desc "Deploy Github artifact to Google Play Store"
  lane :deploy_github_aab_to_play_store do
    upload_to_play_store(
      skip_upload_apk: true,
      track: 'internal',
      aab: 'release-aab/app-release.aab'
    )
  end

  # Uses aab path for local build
  desc "Deploy local artifact to Google Play Store"
  lane :deploy_local_aab_to_play_store do
    upload_to_play_store(
      skip_upload_apk: true,
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Increment version code"
  lane :increment_vc do
    increment_version_code(
      gradle_file_path: "./app/build.gradle.kts",
    )
  end

  desc "Increment version name"
  lane :increment_vn do
    increment_version_name(
      gradle_file_path: "./app/build.gradle.kts",
      version_name: File.read("../VERSION")
    )
  end
end
