name: Fastlane test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  test:
    name: Fastlane Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup java environment
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Setup ruby environment (for fastlane)
    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    # Setup fastlane
    - name: Setup fastlane
      run: bundle install

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Load Maps API Key from secrets
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo MAPS_API_KEY=\"$MAPS_API_KEY\" > ./local.properties

    - name: Load Firebase config file from secrets
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > /home/runner/work/xpense/xpense/app/google-services.json

    # Run tests
    - name: Run tests
      run: bundle exec fastlane test

    # Upload html report to artifacts
#    - name: Upload html report to artifacts
#      uses: actions/upload-artifact@v1
#      with:
#        name: results
#        path: app/build/reports

    # source: https://github.com/marketplace/actions/publish-unit-test-results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "app/build/test-results/**/*.xml"
